### ISSUE TITLE
Difference in colour/transparency between Firefox and IE7

### ISSUE THREAD

**Issue by ramasaig** [LeaVerou/rgba.php#6]
This looks like a great solution, and I've got it working OK. However, using the parameters from the first version (posted Feb 2009) I'm getting very different results between Firefox 8 and IE7.
The parameters are:
    background: url(../inc/rgba.php?r=255&g=100&b=0&a=50) repeat;
    background-color: rgba(255,100,0,0.5);

IE7 uses the first, and Firefox the second. The image in Firefox is much LESS transparent, and I have to change the transparency to '0.2' to get a result comparable to that in IE7. If I comment out the second line I get the same result in both browsers.

**Comment by LeaVerou** [comment]
You are using the fallback incorrectly.
`background` sets **all** background properties, and thus, you are setting `background-image` to the generated one. Then you override `background-color` (which was set to `transparent` from the first declaration) with the RGBA color. So, in modern browsers, you have TWO overlapping layers of the same thing. You have to use `background` for both for it to work correctly.

**Comment by ramasaig** [comment]
Gosh, that was quick !!  Thank you.

Yes, I already had the second line in the CSS (which of course didn't 
work in IE), and I just copied the settings into it.  I see from your 
explanation exactly what has happened.

Many thanks.

Tim Dawson

On 25/02/2012 01:42, Lea Verou wrote:

> You are using the fallback incorrectly.
> `background` sets **all** background properties, and thus, you are setting `background-image` to the generated one. Then you override `background-color` (which was set to `transparent` from the first declaration) with the RGBA color. So, in modern browsers, you have TWO overlapping layers of the same thing. You have to use `background` for both for it to work correctly.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LeaVerou/rgba.php/issues/6#issuecomment-4168688

## 

Tim Dawson
Maolbhuidhe
Fionnphort
Isle of Mull  PA66 6BP

01681 700718
